/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/carabiner+clip+3d+model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/carabiner+clip+3d+model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_c3757f50-3775-47d2-9ac7-4bbaf1096275'].geometry} material={materials['tripo_mat_c3757f50-3775-47d2-9ac7-4bbaf1096275']} />
    </group>
  )
}

useGLTF.preload('/carabiner+clip+3d+model.glb')
